"""Apply — turn a previewed patch into a branch, a commit, and a pull request.

This is the only part of pipewright that changes anything, so it is deliberately
cautious:

* It only ever works inside a git repository.
* It refuses if the target file has uncommitted changes (nothing is clobbered).
* Every change lands on a *new* branch — ``main`` is never touched.
* All pre-flight checks run before any mutation; if a later step fails, the
  branch and the working tree are rolled back.

Pushing and opening the PR are best-effort: if there's no remote or the GitHub
CLI isn't available, the commit still exists locally and we print the exact
commands to finish by hand.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from pipewright.patch import PatchResult

_BRANCH_STEM = "pipewright/ci-tuneup"
_PR_TITLE = "Tune up CI pipeline (pipewright)"


@dataclass
class ApplyOutcome:
    ok: bool
    branch: str | None = None
    base: str | None = None
    committed: bool = False
    pushed: bool = False
    pr_url: str | None = None
    compare_url: str | None = None
    message: str = ""
    error: str | None = None


# --- thin git helpers --------------------------------------------------


def _git(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=str(cwd), capture_output=True, text=True
    )


def repo_root(path: Path) -> Path | None:
    start = path if path.is_dir() else path.parent
    if not start.exists():
        return None
    result = _git(["rev-parse", "--show-toplevel"], start)
    return Path(result.stdout.strip()) if result.returncode == 0 else None


def current_branch(root: Path) -> str | None:
    result = _git(["rev-parse", "--abbrev-ref", "HEAD"], root)
    name = result.stdout.strip()
    return name if result.returncode == 0 and name else None


def _identity_set(root: Path) -> bool:
    name = _git(["config", "user.name"], root).stdout.strip()
    email = _git(["config", "user.email"], root).stdout.strip()
    return bool(name) and bool(email)


def _is_dirty(root: Path, target: Path) -> bool:
    result = _git(["status", "--porcelain", "--", str(target)], root)
    return bool(result.stdout.strip())


def _branch_exists(root: Path, name: str) -> bool:
    result = _git(["rev-parse", "--verify", "--quiet", f"refs/heads/{name}"], root)
    return result.returncode == 0


def _unique_branch(root: Path, stem: str = _BRANCH_STEM) -> str:
    name, i = stem, 2
    while _branch_exists(root, name):
        name = f"{stem}-{i}"
        i += 1
    return name


def _remote_https(root: Path) -> str | None:
    result = _git(["remote", "get-url", "origin"], root)
    if result.returncode != 0:
        return None
    url = result.stdout.strip()
    if url.startswith("git@") and ":" in url:
        host, path = url[4:].split(":", 1)
        url = f"https://{host}/{path}"
    if url.endswith(".git"):
        url = url[:-4]
    return url or None


def compare_url(root: Path, base: str | None, branch: str) -> str | None:
    remote = _remote_https(root)
    if not remote or not base:
        return None
    return f"{remote}/compare/{base}...{branch}?expand=1"


# --- message composition ----------------------------------------------


def _commit_message(result: PatchResult) -> str:
    bullets = "\n".join(f"- {f.title}" for f in result.applied)
    return f"ci: tune up CI pipeline with pipewright\n\nApplies safe CI optimizations:\n{bullets}\n"


def _pr_body(result: PatchResult) -> str:
    lines = ["Generated by pipewright.", "", "## Applied"]
    lines += [f"- {f.title}" for f in result.applied]
    if result.manual:
        lines += ["", "## Suggested (do by hand)"]
        lines += [f"- **{f.title}** — {f.detail}" for f in result.manual]
    return "\n".join(lines)


def _open_pr(root: Path, base: str | None, branch: str, result: PatchResult) -> str | None:
    if shutil.which("gh") is None:
        return None
    args = [
        "pr", "create",
        "--base", base or "main",
        "--head", branch,
        "--title", _PR_TITLE,
        "--body", _pr_body(result),
    ]
    result_proc = subprocess.run(
        ["gh", *args], cwd=str(root), capture_output=True, text=True
    )
    if result_proc.returncode != 0:
        return None
    lines = [ln.strip() for ln in result_proc.stdout.splitlines() if ln.strip()]
    return lines[-1] if lines else None


# --- the one public entry point ---------------------------------------


def apply_patch(
    result: PatchResult,
    *,
    push: bool = True,
    open_pr: bool = True,
    branch: str | None = None,
) -> ApplyOutcome:
    if result.target is None or not result.changed:
        return ApplyOutcome(ok=False, message="No changes to apply.")

    target = Path(result.target).resolve()
    root = repo_root(target)

    # --- pre-flight: fail before mutating anything ---
    if root is None:
        return ApplyOutcome(
            ok=False,
            message="Not a git repository — pipewright only makes changes inside version control.",
        )
    if not _identity_set(root):
        return ApplyOutcome(
            ok=False,
            message="Git needs an identity first. Set it with:\n"
            '  git config user.name "Your Name"\n'
            '  git config user.email "you@example.com"',
        )
    if _is_dirty(root, target):
        return ApplyOutcome(
            ok=False,
            message=f"{target.name} has uncommitted changes — commit or stash them "
            "first so nothing is lost.",
        )

    base = current_branch(root)
    branch = branch or _unique_branch(root)

    created = _git(["checkout", "-b", branch], root)
    if created.returncode != 0:
        return ApplyOutcome(
            ok=False,
            error=created.stderr.strip(),
            message=f"Couldn't create branch {branch}.",
        )

    # --- mutate; roll back on any failure ---
    try:
        target.write_text(result.new_text, encoding="utf-8")
        _git(["add", str(target)], root)
        committed = _git(["commit", "-m", _commit_message(result)], root)
        if committed.returncode != 0:
            raise RuntimeError(committed.stderr.strip() or "git commit failed")
    except Exception as exc:  # noqa: BLE001 - we want to roll back on anything
        _git(["reset", "--hard", "HEAD"], root)
        if base:
            _git(["checkout", base], root)
        _git(["branch", "-D", branch], root)
        return ApplyOutcome(
            ok=False,
            error=str(exc),
            message="Couldn't commit the changes — rolled back, nothing left behind.",
        )

    outcome = ApplyOutcome(ok=True, branch=branch, base=base, committed=True)

    if push:
        pushed = _git(["push", "-u", "origin", branch], root)
        outcome.pushed = pushed.returncode == 0
        if not outcome.pushed:
            outcome.error = pushed.stderr.strip() or None

    if open_pr and outcome.pushed:
        outcome.pr_url = _open_pr(root, base, branch, result)

    outcome.compare_url = compare_url(root, base, branch)
    return outcome
